//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 07:22:17 PM CST 
//


package navicure.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the navicure.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SecurityHeaderElement_QNAME = new QName("http://www.navicure.com/2009/11/NavicureSubmissionService", "SecurityHeaderElement");
    private final static QName _SubmitAnsiSingleRequestElement_QNAME = new QName("http://www.navicure.com/2009/11/NavicureSubmissionService", "SubmitAnsiSingleRequestElement");
    private final static QName _SubmitAnsiSingleResponseElement_QNAME = new QName("http://www.navicure.com/2009/11/NavicureSubmissionService", "SubmitAnsiSingleResponseElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: navicure.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SecurityHeaderType }
     * 
     */
    public SecurityHeaderType createSecurityHeaderType() {
        return new SecurityHeaderType();
    }

    /**
     * Create an instance of {@link SubmitRequestType }
     * 
     */
    public SubmitRequestType createSubmitRequestType() {
        return new SubmitRequestType();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link StatusHeaderType }
     * 
     */
    public StatusHeaderType createStatusHeaderType() {
        return new StatusHeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.navicure.com/2009/11/NavicureSubmissionService", name = "SecurityHeaderElement")
    public JAXBElement<SecurityHeaderType> createSecurityHeaderElement(SecurityHeaderType value) {
        return new JAXBElement<SecurityHeaderType>(_SecurityHeaderElement_QNAME, SecurityHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmitRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.navicure.com/2009/11/NavicureSubmissionService", name = "SubmitAnsiSingleRequestElement")
    public JAXBElement<SubmitRequestType> createSubmitAnsiSingleRequestElement(SubmitRequestType value) {
        return new JAXBElement<SubmitRequestType>(_SubmitAnsiSingleRequestElement_QNAME, SubmitRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.navicure.com/2009/11/NavicureSubmissionService", name = "SubmitAnsiSingleResponseElement")
    public JAXBElement<ResponseType> createSubmitAnsiSingleResponseElement(ResponseType value) {
        return new JAXBElement<ResponseType>(_SubmitAnsiSingleResponseElement_QNAME, ResponseType.class, null, value);
    }

}
