//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 07:22:17 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.navicure.com/2009/11/NavicureSubmissionService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package navicure.wsdl;
