//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 07:22:17 PM CST 
//


package navicure.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactionTyp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="submitterSubmissionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="systemSubmissionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="submittedAnsiVersion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="resultAnsiVersion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="payload" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="processedRealTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="statusHeader" type="{http://www.navicure.com/2009/11/NavicureSubmissionService}StatusHeaderType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseType", propOrder = {
    "transactionTyp",
    "submitterSubmissionId",
    "systemSubmissionId",
    "submittedAnsiVersion",
    "resultAnsiVersion",
    "payload",
    "processedRealTime",
    "statusHeader"
})
public class ResponseType {

    @XmlElement(required = true, nillable = true)
    protected String transactionTyp;
    @XmlElement(required = true, nillable = true)
    protected String submitterSubmissionId;
    @XmlElement(required = true, nillable = true)
    protected String systemSubmissionId;
    @XmlElement(required = true, nillable = true)
    protected String submittedAnsiVersion;
    @XmlElement(required = true)
    protected String resultAnsiVersion;
    @XmlElement(required = true)
    protected String payload;
    @XmlElement(required = true)
    protected String processedRealTime;
    @XmlElement(required = true)
    protected StatusHeaderType statusHeader;

    /**
     * Gets the value of the transactionTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionTyp() {
        return transactionTyp;
    }

    /**
     * Sets the value of the transactionTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionTyp(String value) {
        this.transactionTyp = value;
    }

    /**
     * Gets the value of the submitterSubmissionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmitterSubmissionId() {
        return submitterSubmissionId;
    }

    /**
     * Sets the value of the submitterSubmissionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmitterSubmissionId(String value) {
        this.submitterSubmissionId = value;
    }

    /**
     * Gets the value of the systemSubmissionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemSubmissionId() {
        return systemSubmissionId;
    }

    /**
     * Sets the value of the systemSubmissionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemSubmissionId(String value) {
        this.systemSubmissionId = value;
    }

    /**
     * Gets the value of the submittedAnsiVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmittedAnsiVersion() {
        return submittedAnsiVersion;
    }

    /**
     * Sets the value of the submittedAnsiVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmittedAnsiVersion(String value) {
        this.submittedAnsiVersion = value;
    }

    /**
     * Gets the value of the resultAnsiVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultAnsiVersion() {
        return resultAnsiVersion;
    }

    /**
     * Sets the value of the resultAnsiVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultAnsiVersion(String value) {
        this.resultAnsiVersion = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayload(String value) {
        this.payload = value;
    }

    /**
     * Gets the value of the processedRealTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessedRealTime() {
        return processedRealTime;
    }

    /**
     * Sets the value of the processedRealTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessedRealTime(String value) {
        this.processedRealTime = value;
    }

    /**
     * Gets the value of the statusHeader property.
     * 
     * @return
     *     possible object is
     *     {@link StatusHeaderType }
     *     
     */
    public StatusHeaderType getStatusHeader() {
        return statusHeader;
    }

    /**
     * Sets the value of the statusHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusHeaderType }
     *     
     */
    public void setStatusHeader(StatusHeaderType value) {
        this.statusHeader = value;
    }

}
